package com.example.demo.student;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.Period;

@Entity // maps to database (Hibernate)
@Table // table in our database
public class Student {
    @Id
    @SequenceGenerator( // what does this mean?
            name = "student_sequence",
            sequenceName = "student_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "student_sequence" // the sequence we created
    )
    private Long id;
    private String name;
    private String email;

    @Transient // means this is part of the class, but not in the database.
    private Integer age;

    private LocalDate dob;

    public Student() { // NO ARGUMENT CONSTRUCTOR
    }

    // FULL CONSTRUCTOR
//    public Student(Long id, String name, String email, Integer age, LocalDate dob) {
    public Student(Long id, String name, String email, LocalDate dob) {
        this.id = id;
        this.name = name;
        this.email = email;
        //this.age = age;
        this.dob = dob;
    }

    // NO ID CONSTRUCTOR (FOR OBJECTS GENERATED BY THE DATABASE)
//    public Student(String name, String email, Integer age, LocalDate dob) {
    public Student(String name, String email, LocalDate dob) {
        this.name = name;
        this.email = email;
        //this.age = age;
        this.dob = dob;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getAge() {
        return Period.between(this.dob, LocalDate.now()).getYears();
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public LocalDate getDob() {
        return dob;
    }

    public void setDob(LocalDate dob) {
        this.dob = dob;
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
//                ", age=" + age +
                ", dob=" + dob +
                '}';
    }
}
